apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: safety-amp-prod
resources:
  - ../../base
images:
  - name: iiusacr.azurecr.io/safety-amp-agent
    newTag: latest
patchesStrategicMerge:
  - patch-env.yaml
