apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - safety-amp-complete.yaml
  - dashboard-deployment.yaml
images:
  - name: safety-amp/app
    newName: iiusacr.azurecr.io/safety-amp-agent
    newTag: latest
  - name: ops-dashboard
    newName: iiusacr.azurecr.io/ops-dashboard
    newTag: latest
