apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: safety-amp-dev
images:
  - name: iiusacr.azurecr.io/safety-amp-agent
    newTag: sha-a61f57d
  - name: iiusacr.azurecr.io/ops-dashboard
    newTag: sha-a61f57d
