apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: safety-amp-dev
images:
  - name: safety-amp-agent
    newName: iiusacr.azurecr.io/safety-amp-agent
    newTag: sha-9343089
  - name: ops-dashboard
    newName: iiusacr.azurecr.io/ops-dashboard
    newTag: sha-9343089
