apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: safety-amp-dev
resources:
  - ../../base
images:
  - name: iiusacr.azurecr.io/safety-amp-agent
    newTag: sha-27f8c4c
patchesStrategicMerge:
  - patch-env.yaml
