apiVersion: v1
kind: ServiceAccount
metadata:
  name: safety-amp-workload-identity-sa
  namespace: safety-amp
  annotations:
    # Dev environment Azure Workload Identity
    azure.workload.identity/client-id: "a2bcb3ce-a89b-43af-804c-e8029e0bafb4"
    azure.workload.identity/tenant-Id: "953922e6-5370-4a01-a3d5-773a30df726b"
