apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: safety-amp-staging
resources:
  - ../../base
images:
  - name: iiusacr.azurecr.io/safety-amp-agent
    newTag: staging
patchesStrategicMerge:
  - patch-env.yaml
